# LOADER
root: './data'
s_batch: 32
u_batch: 64
worker: 8
view: 10
epochs: 200
multi_crop: 6
color_jitter: Ture
gray_scale: Ture
h_flip: Ture
v_flip: False
pin_memory: True
drop_last: True

# MODEL
model_name: wide_resnet28w2
output_dim: 128
use_pred_head: False
only_best: False

# OPTIMIZER
ref_lr: 0.001
min_lr: 0.0001
max_lr: 0.03
weight_decay: 0.0005
momentum: 0.9
warm_up: 30
use_fp: True