# LOADER
S_BATCH: 32
U_BATCH: 64
WORKER: 8
VIEW: 10
SAMPLING: True
STRONG: True
EPOCHS: 200
MULTI_CROP: 6
COLOR_JITTER: Ture
GRAY_SCALE: Ture
H_FLIP: Ture
V_FLIP: False

# MODEL
MODEL: wrnet-28w2
EMBED: 128
USE_PRED: False
ONLY_BEST: False

# OPTIMIZER
REF_LR: 0.001
MIN_LR: 0.0001
MAX_LR: 0.03
WEIGHT_DECAY: 0.0005
MOMENTUM: 0.9
WARM_UP: 30
USE_FP: True